ALTER TABLE [dbo].[Player]
    ADD CONSTRAINT [CK_OnlineName_Platform] UNIQUE NONCLUSTERED ([OnlineName] ASC, [PlatformId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

