ALTER TABLE [dbo].[Difficulty]
    ADD CONSTRAINT [PK_Difficulty] PRIMARY KEY CLUSTERED ([DifficultyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

