ALTER TABLE [dbo].[Game]
    ADD CONSTRAINT [PK_Game] PRIMARY KEY CLUSTERED ([GameId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

