ALTER TABLE [dbo].[Instrument]
    ADD CONSTRAINT [PK_Instrument] PRIMARY KEY CLUSTERED ([InstrumentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

