ALTER TABLE [dbo].[Platform]
    ADD CONSTRAINT [PK_Platform] PRIMARY KEY CLUSTERED ([PlatformId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

