ALTER TABLE [dbo].[Player]
    ADD CONSTRAINT [PK_Player] PRIMARY KEY CLUSTERED ([PlayerId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

