ALTER TABLE [dbo].[ScoreStage]
    ADD CONSTRAINT [PK_ScoreStage] PRIMARY KEY CLUSTERED ([ScoreStageId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



