ALTER TABLE [dbo].[SongInstrumentDifficulty]
    ADD CONSTRAINT [PK_SongInstrumentDifficulty] PRIMARY KEY CLUSTERED ([SongInstrumentDifficultyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

