ALTER TABLE [dbo].[Song]
    ADD CONSTRAINT [PK_Song] PRIMARY KEY CLUSTERED ([SongId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

