ALTER TABLE [dbo].[SongStage]
    ADD CONSTRAINT [PK_SongStage] PRIMARY KEY CLUSTERED ([SongStageId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

